### ISSUE TITLE
DNNER/demo: How can be Mutual Information negative?

### ISSUE THREAD

**Issue by Jamesswiz** [sphinxteam/dnner#6]
Hi...
This is in regard to replication of Fig2 of your paper.

We know the identity for mutual information (MI)
I(X,Y)=H(Y)-H(Y|X) ;  H=entropy
which for a deterministic system gives
I(X,Y)=H(Y)    as H(Y|X)=0

Fig2 in paper plots H(Y) for such a system (neural net with random but fixed weights). While entropy can be negative, MI can not. And for deterministic mapping, H(Y) or MI should not be negative too?

Can you please explain this? or I am misinterpreting your experimental setup.

**Comment by marylou-gabrie** [comment]
Hello Jamesswiz, 
- You are right, mutual information cannot be negative, but it can diverge.
- For X, Y  **continuous** random variables with a deterministic map X -> Y, the conditional entropy H(Y|X) is not equal to 0 but actually to - infinity (entropy of a Dirac distribution), so that I(X,Y) is + infinity. 
- In our experimental setup we are introducing a noise to regularize the avoid the divergence of the mutual information. 

Is this answering your questions ? Do not hesitate to ask again is something remains unclear !

**Comment by Jamesswiz** [comment]
Hi,
Thanks for clarity.
I missed the mutual information experiment in your paper's supplementary section, but I don't see the implementation of conditional entropy H(Y|X) (the integral from eq70 sup:sec1.6.1) to reproduce the result.?

**Comment by andrmnl** [comment]
Hi @Jamesswiz, the extra term on eq. 70 can be obtained directly from the output's `eval_i` method (eq. 34b) evaluated at V = 0, see https://github.com/sphinxteam/dnner/blob/master/dnner/compute_entropy.py#L94. You can plug V = 0 in the Z_L definition (eq. 35c) to show the equivalence.

**Comment by Jamesswiz** [comment]
@ndrmnl 
Thanks for quick support. I now understand the equivalence via eq. 35c.
